#!/bin/sh

pad=$((($(tput cols)/2)-4))
printf "\n\e[0;33m%-${pad}s -%s -\e[0;39m\n\n" " " "~INFO"| tr ' ~' ' ' 
gcc $1 -o test
printf "\n\e[0;34m%-${pad}s -%s -\e[0;39m\n\n" " " "~OUPUT"| tr ' ~' ' '
./${1%%.*}
